# Generated by Django 5.1 on 2024-08-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='competency_level',
        ),
        migrations.CreateModel(
            name='LanguageCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('competency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='users.studentprofile')),
            ],
        ),
    ]
