# Generated by Django 5.1 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studentprofile_competency_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
