# Generated by Django 5.1 on 2024-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_questionnaire_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='languages_taught',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='can_host_in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='can_host_online',
            field=models.BooleanField(default=False),
        ),
    ]
