# Generated by Django 5.1 on 2024-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_teacherprofile_languages_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bookings_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
