# Generated by Django 5.1 on 2024-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_date_joined_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
