# Generated by Django 5.1 on 2024-12-06 11:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_questionnaire_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 6, 11, 52, 8, 779688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='users.studentprofile'),
        ),
    ]
