# Generated by Django 5.1 on 2025-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_questionnaire_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active_advisor',
            field=models.BooleanField(default=True),
        ),
    ]
