# Generated by Django 5.1 on 2025-06-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacherprofile_is_active_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['teacher', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_notes', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
