# Generated by Django 5.1 on 2025-06-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_message'),
        ('users', '0014_resourcenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attachment to share with the student.', upload_to='resource_notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this file was uploaded.')),
            ],
        ),
        migrations.AddField(
            model_name='resourcenote',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Optional: associate with a particular meeting.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='resourcenote',
            name='title',
            field=models.CharField(blank=True, help_text="Optional summary (e.g. 'Pronunciation tips').", max_length=200),
        ),
        migrations.AddField(
            model_name='resourcenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this note was last modified.'),
        ),
        migrations.AlterField(
            model_name='resourcenote',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Which teacher/admin wrote this note; null if user deleted.', limit_choices_to=models.Q(('role__in', ['teacher', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcenote',
            name='content',
            field=models.TextField(help_text='Rich-text HTML (from CKEditor).'),
        ),
        migrations.AlterField(
            model_name='resourcenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this note was first created.'),
        ),
        migrations.AlterField(
            model_name='resourcenote',
            name='student_profile',
            field=models.ForeignKey(help_text='The student who will see this note.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_notes', to='users.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='resourcenote',
            index=models.Index(fields=['student_profile', 'created_at'], name='users_resou_student_96b90b_idx'),
        ),
        migrations.AddField(
            model_name='resourceattachment',
            name='note',
            field=models.ForeignKey(help_text='The note this file augments.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.resourcenote'),
        ),
    ]
