# Generated by Django 5.1 on 2025-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_resourceattachment_resourcenote_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcenote',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='faculty_department',
            field=models.CharField(default='External', help_text="Enter your faculty or department. If none, type 'External'.", max_length=150),
            preserve_default=False,
        ),
    ]
