# Generated by Django 5.1 on 2025-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_resourcenote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='mother_tongue',
            field=models.CharField(default='Not provided', help_text='Enter your first/native language. If multilingual, list them separated by commas.', max_length=100),
            preserve_default=False,
        ),
    ]
