# Generated by Django 5.1 on 2025-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_questionnaire_university_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='language_mandatory_goals',
            field=models.JSONField(default=list, help_text='List of learning/development goals selected for this language.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='language_mandatory_name',
            field=models.CharField(default='Not specified', help_text='Specify the main language you wish to learn or improve.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='language_mandatory_proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
            preserve_default=False,
        ),
    ]
