# Generated by Django 5.1 on 2025-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_questionnaire_language_mandatory_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='language_optional_goals',
            field=models.JSONField(blank=True, help_text='List of learning/development goals selected for this additional language.', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='language_optional_name',
            field=models.CharField(blank=True, help_text='Specify an additional language you wish to learn or improve (optional).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='language_optional_proficiency',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
