# Generated by Django 5.1 on 2025-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_questionnaire_language_optional_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='aspects_to_improve',
            field=models.TextField(default='Not specified', help_text='What specific aspects of the language(s) would you like to learn or improve?'),
            preserve_default=False,
        ),
    ]
