# Generated by Django 5.1 on 2025-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_questionnaire_aspects_to_improve'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='activities_you_can_manage',
            field=models.TextField(blank=True, help_text='E.g. reading newspapers, watching films without subtitles, giving presentations, holding casual conversations.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='aspects_to_improve',
            field=models.TextField(help_text='What specific aspects of the language(s) would you like to learn or improve?', max_length=2000),
        ),
    ]
