# Generated by Django 5.1 on 2025-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_questionnaire_activities_you_can_manage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='activities_you_can_manage',
            field=models.TextField(default='Not specified', help_text='E.g. reading newspapers, watching films without subtitles, giving presentations, holding casual conversations.', max_length=2000),
            preserve_default=False,
        ),
    ]
