# Generated by Django 5.1 on 2025-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_questionnaire_activities_you_can_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='hours_per_week',
            field=models.CharField(default='Not Specified', help_text='Roughly how many hours per week will you devote to language learning?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='activities_you_can_manage',
            field=models.TextField(help_text='List the activities you can manage in the language(s) (if applicable)', max_length=2000),
        ),
    ]
