# Generated by Django 5.1 on 2025-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_questionnaire_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='other_languages_studied',
            field=models.TextField(blank=True, help_text='List any other languages you have previously studied (optional).', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='hours_per_week',
            field=models.CharField(help_text='Roughly how many hours per week will you devote to language learning?', max_length=300),
        ),
    ]
