# Generated by Django 5.1 on 2025-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_questionnaire_other_languages_studied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question2',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Any final comments you’d like to share with us (optional).', max_length=2000, null=True),
        ),
    ]
