# Generated by Django 5.1 on 2025-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_questionnaire_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='activities_you_can_manage',
            field=models.TextField(help_text='List the activities you can manage in the language(s)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
