# Generated by Django 5.1 on 2025-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_studentprofile_user_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/students/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/teachers/'),
        ),
    ]
