"""
Django settings for languagelink project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from .env (local development convenience)
# This makes os.getenv(...) pick up values from the file advising-team/advising-team/.env
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$(9(oh7tm+*s&grrr(z_5v21mye-j8xo@$-=ni6m7=pae#+t=p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  #Third party apps
  "django_ckeditor_5",
  # Custom Apps
  'core',
  'users',
  'booking',
  'notifications',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'languagelink.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'languagelink.wsgi.application'

# Database
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
  }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
# Block slots that start in the past or too soon (minutes)
BOOKING_LEAD_MINUTES = 60  # set 0 if you only want to block past, not "soon"
TIME_ZONE = "Europe/London"  # (ensure this is set)
USE_TZ = True

USE_I18N = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
  BASE_DIR / 'static',  # Includes static directory at the root level
  BASE_DIR / 'core/static',  # Includes static directory inside core app
]

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Specify custom user model
AUTH_USER_MODEL = 'users.CustomUser'

#Configure which toolbar items you want in CKEDITOR_5
CKEDITOR_5_CONFIGS = {
  "default": {
    "toolbar": [
      "bold","italic","link","bulletedList","numberedList",
    ],
    "heading": False,
    "removePlugins": [
      "CKBox","CKFinder","EasyImage",
      "RealTimeCollaborativeComments",
      "RealTimeCollaborativeTrackChanges",
      "RealTimeCollaborativeRevisionHistory",
      "Comments","TrackChanges","TrackChangesData",
      "RevisionHistory","Pagination","WProofreader",
      "MathType",
    ],
  }
}



# Add Trusted Origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
  'http://localhost:8000',
  'http://127.0.0.1:8000',
  'http://localhost:3000',
  'http://127.0.0.1:3000',
]


LOGIN_URL = "/users/login/"
LOGIN_REDIRECT_URL = "/users/student/profile/"  # optional: where to go after login if a view uses LoginRequired
LOGOUT_REDIRECT_URL = "/"                      # optional: already done via LogoutView(next_page='/')


# 3 days (seconds); Django’s default is already ~72h
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", 60 * 60 * 72))


# -------------------------------
# Email configuration
# Purpose:
#  - In development, use a safe backend (console/file) so no real emails are sent.
#  - In production, flip to University SMTP via environment variables only.
#  - Keep a single source for From address and a site URL for links in emails.
# -------------------------------

# Who the email appears to be from (adjust the address if needed)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "LanguageLink <no-reply@langcen.cam.ac.uk>")

# Optional: prefix subjects to spot app emails in inbox/search
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[LanguageLink] ")

# Sender for Django's internal error emails (defaults to DEFAULT_FROM_EMAIL)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Choose the email backend by environment variable.
# Dev default: console backend prints full emails to the runserver console.
EMAIL_BACKEND = os.getenv(
  "EMAIL_BACKEND",
  "django.core.mail.backends.console.EmailBackend"
)

# Path used by the file-based email backend (only if you enable that backend)
EMAIL_FILE_PATH = os.getenv("EMAIL_FILE_PATH", str(BASE_DIR / "tmp_emails"))


# SMTP settings are only used if EMAIL_BACKEND is set to the SMTP backend.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

# Base URL used to build absolute links inside emails when no request is available.
# Dev default points at your local server.
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")
