# Generated by Django 5.1 on 2025-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheravailability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
