# Generated by Django 5.1 on 2025-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_teacheravailability_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.CharField(blank=True, help_text='Optional message from student when booking this slot.', max_length=300, null=True),
        ),
    ]
